config/routes.rb
PaymentServer::Application.routes.draw do

  get "friends/show"

  get "friends/create"

  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'transaction#balance'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/users/valid', to: 'users#valid', via: :post

  match '/transfer', to: 'transaction#create', via: :post
  match '/transfer', to: 'transaction#new', via: :get
  match '/transfer/new', to: 'transaction#form', via: :get
  match '/transactions(/:id)', to: 'transaction#transactions', :as => :transactions
  match '/balance', to: 'transaction#balance', via: :get

  match '/token', to: 'transaction#token', via: :get
  match '/token', to: 'transaction#gen_token', via: :post
  match '/token', to: 'transaction#put_token', via: :put

  match '/friends', to: 'friends#show', via: :get
  match '/friends', to: 'friends#create', via: :post

  get '/sessions', to: redirect('/')
  get '/signout', to: redirect('/signin')

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	
  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end

  def new
  end

  def edit
    @user = User.find_by_remember_token!(params[:id])
  end

  def update
    @user = User.find_by_remember_token!(params[:id])
    @user.updating_password = true
    if @user.update_attributes(params[:user])
       redirect_to root_url, :notice => "Password has been reset!"
    else
       render :edit
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Password Reset') %>
<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
      <div class="form-element qp-name-row">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="form-element qp-name-row">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
    </div>
    <div class="ui-grid-a">
      <div class="ui-block-a">
        <%= link_to 'Cancel', root_path, :class => 'cancel secondary-button', 'data-role' => "button",
                    'data-theme' => 'dva', 'data-icon' => "back" %>
      </div>
      <div class="ui-block-b">
        <%= f.submit "Update Password", 'data-role' => "button", 'data-theme' => 'dva',
                     'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
      </div>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<% provide(:title, 'Password Reset') %>
<%= form_tag password_resets_path, :method => :post do %>
    <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
      <div class="form-element qp-name-row">
        <%= label_tag :email, 'Please enter the Email associated with your Account:' %>
        <%= text_field_tag :email, params[:email] %>
      </div>
    </div>
    <div class="ui-grid-a">
      <div class="ui-block-a">
        <%= link_to 'Cancel', root_path, :class => 'cancel secondary-button', 'data-role' => "button",
                    'data-theme' => 'dva', 'data-icon' => "back" %>
      </div>
      <div class="ui-block-b"><%= submit_tag "Reset Password", 'data-role' => "button", 'data-theme' => 'dva',
                                             'data-icon' => "arrow-r", 'data-iconpos' => "right" %></div>
    </div>
<% end %>