config/routes.rb
PaymentServer::Application.routes.draw do

  get "friends/show"

  get "friends/create"

  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'transaction#balance'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/users/valid', to: 'users#valid', via: :post

  match '/transfer', to: 'transaction#create', via: :post
  match '/transfer', to: 'transaction#new', via: :get
  match '/transfer/new', to: 'transaction#form', via: :get
  match '/transactions(/:id)', to: 'transaction#transactions', :as => :transactions
  match '/balance', to: 'transaction#balance', via: :get

  match '/token', to: 'transaction#token', via: :get
  match '/token', to: 'transaction#gen_token', via: :post
  match '/token', to: 'transaction#put_token', via: :put

  match '/friends', to: 'friends#show', via: :get
  match '/friends', to: 'friends#create', via: :post

  get '/sessions', to: redirect('/')
  get '/signout', to: redirect('/signin')

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :username, :name, :password, :password_confirmation, :admin
  has_secure_password
  has_many :accounts, dependent: :destroy
  has_many :transactions, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates_presence_of :email, :on => :create
  validates_presence_of :username, :on => :create
  validates_presence_of :name, :on => :create

  validates :name, length: {maximum: 50}, :if => Proc.new { !:name.nil? }
  validates :username, length: {maximum: 50}, uniqueness: true, :if => Proc.new { !:username.nil? }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false},
            :if => Proc.new { !:email.nil? }
  validates :password, length: {minimum: 6}, :if => :should_validate_password?
  validates :password_confirmation, presence: true, :if => :should_validate_password?

  attr_accessor :updating_password

  def send_password_reset
    create_remember_token
    save!
    UserMailer.password_reset(self).deliver
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def should_validate_password?
    updating_password || new_record?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :show]
  before_filter :admin_user, only: :index
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        render json: @users.collect {
            |a| {:name => a.name, :email => a.email, :username => a.username}
        }, status: :ok
      }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user, status: :ok }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user, status: :ok }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        account =Account.new(:balance => 500, :user_id => @user.id, :name => 'CHECKING')
        account.save
        transaction = Transaction.new(:amount => 500, :balance => 500, :toAccount => account.number,
                                      :fromAccount => 'admin@apps.loginto.me', :user_id => @user.id,
                                      :account_id => account.id, :memo => "Don't spend it all in one place")
        transaction.save
        account2 =Account.new(:balance => 2500, :user_id => @user.id, :name => 'SAVINGS')
        account2.save
        transaction2 = Transaction.new(:amount => 2500, :balance => 2500, :toAccount => account2.number,
                                       :fromAccount => 'admin@apps.loginto.me', :user_id => @user.id,
                                       :account_id => account2.id, :memo => "Don't spend it all in one place")
        transaction2.save
        sign_in @user
        format.html { redirect_to balance_path, notice: 'User was successfully created.' }
        format.json { render json: {:status => true, :message => ["Welcome #{@user.name}"], :userId => @user.id}, status: :ok }
      else
        format.html { render action: "new" }
        format.json { render json: {:status => false, :message => @user.errors.full_messages, :userId => 0}, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if params[:user].nil?
      respond_to do |format|
        format.html { render action: "edit" }
        format.json { render json: {:status => false, :message => "You didn't change anything", :userId => @user.id}, status: :unprocessable_entity }
      end

    else
      # required for settings form to submit when password is left blank
      if params[:user][:password].blank?
        params[:user].delete("password")
        params[:user].delete("password_confirmation")
      elsif  params[:user][:password]
        @user.updating_password = true
      end

      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render json: {:status => true, :message => ["Thanks for the update #{@user.name}"], :userId => @user.id}, status: :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: {:status => false, :message => @user.errors.full_messages, :userId => @user.id}, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "You will be missed #{@user.name}" }
      format.json { render json: {:status => true, :message => ["You will be missed #{@user.name}"], :userId => @user.id}, status: :ok }
    end
  end

  # POST /users/valid
  # POST /users/valid.json
  def valid
    check = User.find_by_email(params[:email])
    if check
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: {:status => true, :message => ["#{check.username}"]} }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render json: {:status => false, :message => ["The user does not exist"]} }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
      <div class="form-element qp-name-row">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-element qp-name-row">
        <%= f.label :username %>
        <%= f.text_field :username %>
      </div>
      <div class="form-element qp-name-row">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="form-element qp-name-row">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="form-element qp-name-row">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>
      </div>
    </div>
    <div class="ui-grid-a">
      <div class="ui-block-a">
        <%= link_to 'Cancel', root_path, :class => 'cancel secondary-button', 'data-role' => "button",
                    'data-theme' => 'dva', 'data-icon' => "back" %>
      </div>
      <div class="ui-block-b">
        <%= f.submit 'Submit', 'data-role' => "button", 'data-theme' => 'dva',
                     'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
      </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Profile') %>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'Profile') %>

<div class="ui-grid-b">
  <table data-role="table" class="ui-body-d ui-shadow table-stripe ui-responsive">
    <thead>
    <tr class="ui-bar-d">
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Show', user, 'data-role' => "button", 'data-icon' => "arrow-r", 'data-iconpos' => "notext", 'data-inline' => "true" %></td>
          <td><%= link_to 'Edit', edit_user_path(user), 'data-role' => "button", 'data-icon' => "info", 'data-iconpos' => "notext", 'data-inline' => "true" %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}, 'data-role' => "button", 'data-icon' => "delete", 'data-iconpos' => "notext", 'data-inline' => "true" %></td>
        </tr>
    <% end %>
    </table>
</div>
<br/>

<%= link_to 'New User', new_user_path, 'data-role' => "button", 'data-inline' => "true" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<div class="unshuttered">
  <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
    <p style="font-size: 18px;">
      <small style="font-weight: normal;color: #7f8c8d;">Name:</small>
      &nbsp;<%= @user.name %></p>
    <p style="font-size: 18px;">
      <small style="font-weight: normal;color: #7f8c8d;">Email:&nbsp;</small>
      &nbsp;<%= @user.email %></p>
    <br/>
    <hr/>
    <br/>
    <% if admin? %>
        <div class="ui-grid-a">
          <div class="ui-block-a">
            <%= link_to 'All Users', users_path, 'data-role' => "button", 'data-theme' => "dva",
                        'data-icon' => "arrow-l", 'data-iconpos' => "left" %>
          </div>
          <div class="ui-block-b">
            <%= link_to 'Edit profile', edit_user_path(@user), 'data-role' => "button", 'data-icon' => "edit",
                        'data-theme' => "dva", 'data-iconpos' => "right" %>
          </div>
        </div>
    <% else %>
        <%= link_to 'Edit profile', edit_user_path(@user), 'data-role' => "button", 'data-icon' => "edit",
                    'data-theme' => "dva", 'data-iconpos' => "right" %>
    <% end %>
  </div>
</div>