config/routes.rb
PaymentServer::Application.routes.draw do

  get "friends/show"

  get "friends/create"

  resources :password_resets, only: [:new, :create, :update, :edit]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'transaction#balance'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/users/valid', to: 'users#valid', via: :post

  match '/transfer', to: 'transaction#create', via: :post
  match '/transfer', to: 'transaction#new', via: :get
  match '/transfer/new', to: 'transaction#form', via: :get
  match '/transactions(/:id)', to: 'transaction#transactions', :as => :transactions
  match '/balance', to: 'transaction#balance', via: :get

  match '/token', to: 'transaction#token', via: :get
  match '/token', to: 'transaction#gen_token', via: :post
  match '/token', to: 'transaction#put_token', via: :put

  match '/friends', to: 'friends#show', via: :get
  match '/friends', to: 'friends#create', via: :post

  get '/sessions', to: redirect('/')
  get '/signout', to: redirect('/signin')

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
  before_filter :signed_in_user

  # GET /transfer
  def new
    @transaction = Transaction.new
    @user = current_user
    @accounts = Account.find_all_by_user_id(@user.id).collect {
        |a| ["#{a.name.capitalize} Account (...#{a.number.match(/(.{0,#{4}}$)/)}):  $#{a.balance}", a.number]
    }
  end

  # GET /transfer/new
  def form
    @transaction = Transaction.new
    @user = current_user
    @accounts = Account.find_all_by_user_id(@user.id).collect {
        |a| ["#{a.name.capitalize} Account (...#{a.number.match(/(.{0,#{4}}$)/)}):  $#{a.balance}", a.number]
    }
  end

  # POST /transfer
  # POST /transfer.json
  def create
    @transaction = Transaction.new(params[:transfer])
    @user = current_user
    @accounts = Account.find_all_by_user_id(@user.id).collect {
        |a| ["#{a.name.capitalize} Account (...#{a.number.match(/(.{0,#{4}}$)/)}):  $#{a.balance}", a.number]
    }

    #Autoset fromAccount if not present
    @transaction.fromAccount ||= @user.email

    #set accounts
    @account = Account.find_by_number(@transaction.fromAccount)
    @account ||= Account.find_by_user_id(User.find_by_email(@transaction.fromAccount))
    toAccount = Account.find_by_number(@transaction.toAccount)
    toAccount ||= Account.find_by_user_id(User.find_by_email(@transaction.toAccount))

    respond_to do |format|
      if toAccount && @account
        if toAccount.id != @account.id && @transaction.amount > 0 && @account.user_id == @user.id
          #set up transactions
          @transaction.user_id=@user.id
          @transaction.account_id = @account.id
          otherTransaction = Transaction.new(:amount => @transaction.amount, :toAccount => @transaction.toAccount,
                                             :fromAccount => @transaction.fromAccount, :user_id => toAccount.user_id,
                                             :account_id => toAccount.id, :memo => @transaction.memo)
          @transaction.amount = -@transaction.amount
          #update the account balance
          @transaction.balance = @account.balance + @transaction.amount
          otherTransaction.balance = toAccount.balance + otherTransaction.amount

          #update Friends
          new_friend = Friends.new(:user_id => @user.id, :friend_user_id => toAccount.user_id)
          new_friend.save

          if  @transaction.save
            otherTransaction.save
            if @account.update_attributes({:balance => @transaction.balance})
              if  toAccount.update_attributes({:balance => otherTransaction.balance})
                format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
                format.json { render json: {:status => true, :message => ["Transaction successful"],
                                            :userId => current_user.id}, status: :ok }
              else
                format.html { render action: "new", notice: "Something went wrong" }
                format.json { render json: {:status => false, :message => toAccount.errors.full_messages, :userId => 0},
                                     status: :unprocessable_entity }
              end
            else
              format.html { render action: "new", notice: "Something went wrong" }
              format.json { render json: {:status => false, :message => @account.errors.full_messages, :userId => 0},
                                   status: :unprocessable_entity }
            end
          else
            format.html { render action: "new", notice: "Something went wrong" }
            format.json { render json: {:status => false, :message => @transaction.errors.full_messages, :userId => 0},
                                 status: :unprocessable_entity }
          end
        else
          format.html { render action: "new", notice: "The information supplied is not correct" }
          format.json { render json: {:status => false, :message => ["The information supplied is not correct"],
                                      :userId => 0}, status: :unprocessable_entity }
        end
      else
        format.html { render action: "new", notice: "The information supplied is not correct" }
        format.json { render json: {:status => false, :message => ["The account information supplied is not correct"],
                                    :userId => 0}, status: :unprocessable_entity }
      end
    end
  end

  #/transactions
  #/transactions.json
  def transactions
    @user = current_user
    if params[:id]
      @account = Account.find(params[:id])
      if @account.user_id != @user.id
        @account = nil
      end
    else
      @account = Account.find_by_user_id(@user.id)
    end

    respond_to do |format|
      if @account
        @transactions = Transaction.find_all_by_account_id(@account.id)

        format.html { render action: 'index' } # index.html.erb
        format.json { render json: {:transactions => @transactions}, status: :ok }
      else
        format.html { redirect_to root_path, notice: 'Error loading that account' }
        format.json { render json: {:transactions => ['Error loading that account']}, status: :ok }
      end

    end
  end

  #/balance
  #/balance.json
  def balance
    @user = current_user
    @accounts = Account.find_all_by_user_id(@user.id)
    respond_to do |format|
      format.html # balance.html.erb
      format.json { render json: {:accounts => @accounts.collect { |account| {:name => account.name,
                                                                              :number => account.number,
                                                                              :balance => account.balance,
                                                                              :id => account.id} }}, status: :ok }
    end
  end

  # GET /token
  # GET /token.json
  def token
    @token = QRtoken.new
    @user = current_user
    @accounts = Account.find_all_by_user_id(@user.id).collect {
        |a| ["#{a.name.capitalize} Account (...#{a.number.match(/(.{0,#{4}}$)/)}):  $#{a.balance}", a.number]
    }
  end

  # POST /token
  # POST /token.json
  def gen_token
    @user = current_user
    if params[:token][:account_number].blank?
      params[:token].delete("account_number")
    end
    @token = QRtoken.new(params[:token])
    @token.account_number ||= Account.select(:number).where(["user_id = ?", @user.id]).first.number
    @account = Account.find_by_number(@token.account_number)
    respond_to do |format|
      if  @account && @token.amount > 0
        if @account.user_id == @user.id

          if @token.save
            @qr = RQRCode::QRCode.new(@token.token)
            format.html { render action: "qrcode", notice: 'Transaction was successfully created.' }
            format.json { render json: {:status => true, :token => @token.token} }
          else
            format.html { redirect_to token_path, notice: 'The token could not be made' }
            format.json { render json: {:status => false, :token => ""}, status: :unprocessable_entity }
          end
        else
          format.html { redirect_to token_path, notice: 'The token could not be made' }
          format.json { render json: {:status => false, :token => ""}, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to token_path, notice: 'The token could not be made' }
        format.json { render json: {:status => false, :token => ""}, status: :unprocessable_entity }
      end
    end
  end

  # PUT /token
  # PUT /token.json
  def put_token
    @user = current_user
    @token = QRtoken.find_by_token(params[:token])

    respond_to do |format|
      if @token
        @account = Account.find_by_number(@token.account_number)
        toAccount = Account.find_by_number(params[:account])

        if toAccount && @account
          if toAccount.id != @account.id && @token.amount > 0
            #set up transactions
            @transaction = Transaction.new(:amount => -@token.amount, :toAccount => toAccount.number,
                                           :fromAccount => @token.account_number, :user_id => @account.user_id,
                                           :account_id => @account.id, :memo => "token transfer")

            otherTransaction = Transaction.new(:amount => @token.amount, :toAccount => toAccount.number,
                                               :fromAccount => @transaction.fromAccount, :user_id => toAccount.user_id,
                                               :account_id => toAccount.id, :memo => "token transfer")

            #update the account balance
            @transaction.balance = @account.balance + @transaction.amount
            otherTransaction.balance = toAccount.balance + otherTransaction.amount

            #update Friends
            new_friend = Friends.new(:user_id => @user.id, :friend_user_id => toAccount.user_id)
            new_friend.save

            if  @transaction.save
              otherTransaction.save
              if @account.update_attributes({:balance => @transaction.balance})
                if  toAccount.update_attributes({:balance => otherTransaction.balance})
                  @token.destroy
                  format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
                  format.json { render json: {:status => true, :message => ["Transaction successful"]} }
                else
                  format.html { render action: "new", notice: "Something went wrong" }
                  format.json { render json: {:status => false, :message => toAccount.errors.full_messages}, status: :unprocessable_entity }
                end
              else
                format.html { render action: "new", notice: "Something went wrong" }
                format.json { render json: {:status => false, :message => @account.errors.full_messages}, status: :unprocessable_entity }
              end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/transaction/balance.html.erb
<% provide(:title, 'My Accounts') %>
<div id="accountsList">
  <% @accounts.sort_by(&:name).each do |account| %>
      <ul data-inset="true" data-role="listview" data-theme="d" class="ui-listview ui-listview-inset ui-corner-all ui-shadow">
        <li class="ui-btn ui-btn-icon-right ui-li ui-corner-top ui-btn-up-d" data-role="list-divider" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="e">
          <div class="ui-li ui-corner-top">
            <div class="ui-btn-text">
              <h4 style="color: #261c02;text-shadow: 0 -1px 0 #fff;"><%= account.name.upcase %> ACCOUNT
                (...<%= account.number.match(/(.{0,#{4}}$)/) %>)</h4>
            </div>
          </div>
        </li>
        <li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="d" class="ui-btn ui-btn-icon-right ui-li ui-btn-up-d">
          <%= link_to transactions_url(account), :class => 'ui-btn-inner ui-li' do %>
              <div class="ui-btn-text">
                <div class="ui-grid-a">
                  <div class="ui-block-a">
                    <h3 class="ui-li-heading">Available balance</h3>

                    <div class="ui-li-desc" style="color: #7f8c8d;">See activity</div>
                  </div>
                  <div class="ui-block-b">
                    <h3 class="ui-li-heading" style="float: right;padding-right: 20px;color: #176da6;margin-top: 15px;font-size: 20px;">$<%= account.balance %></h3>
                  </div>
                </div>
              </div>
          <% end %>
        </li>
      </ul>
  <% end %>
</div>

app/views/transaction/form.html.erb
<% provide(:title, 'Transfer') %>

<div class="unshuttered">
  <%= form_for(@transaction, :url => transfer_path(@transaction), :as => :transfer) do |f| %>
      <% if @transaction.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction:</h2>

            <ul>
              <% @transaction.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
        <div class="form-element qp-name-row">
          <%= f.label :toAccount, 'Transfer to' %>
          <%= f.text_field :toAccount %>
        </div>
        <div class="form-element qp-name-row">
          <%= f.label :fromAccount, 'Pay from' %>
          <%= f.select :fromAccount, @accounts -%>
        </div>
        <div class="form-element qp-name-row">
          <%= f.label :amount, 'Amount $' %>
          <%= f.text_field :amount, :step => 0.01, :type => 'number' %>
        </div>
        <div class="form-element qp-name-row">
          <%= f.label :memo %>
          <%= f.text_field :memo, :maxlength => 200 %>
        </div>
      </div>
      <div class="ui-grid-a">
        <div class="ui-block-a">
          <%= link_to 'Cancel', root_path, :class => 'cancel secondary-button', 'data-role' => "button",
                      'data-theme' => 'dva', 'data-icon' => "back" %>
        </div>
        <div class="ui-block-b">
          <%= f.submit 'Transfer', 'data-role' => "button", 'data-theme' => 'dva',
                       'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
        </div>
      </div>

  <% end %>

  <%= link_to 'QR Transfer', token_path, 'data-role' => "button", 'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
</div>

app/views/transaction/index.html.erb
<% provide(:title, 'My Accounts') %>

<div id="accountsList">

  <ul data-inset="true" data-role="listview" data-theme="d" class="ui-listview ui-listview-inset ui-corner-all ui-shadow">
    <li class="ui-btn ui-btn-icon-right ui-li ui-corner-top ui-btn-up-d" data-role="list-divider" data-corners="false"
        data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="e">
      <div class="ui-li ui-corner-top">
        <div class="ui-btn-text">
          <h4 style="color: #261c02;text-shadow: 0 -1px 0 #fff;"><span style="float:right;color: #27ae60;">
            Balance: $<%= @account.balance %></span><%= @account.name %> ACCOUNT
            (...<%= @account.number.match(/(.{0,#{4}}$)/) %>)
          </h4>
        </div>
      </div>
    </li>
    <li class="">
      <div class="ui-btn-inner ui-li">
        <div class="ui-btn-text">
          <div class="ui-grid-a">
            <table data-role="table" id="transfer-table-custom" data-mode="reflow" class="transfer-list table-stroke">
              <thead>
              <tr>
                <th data-priority="1">Sent to</th>
                <th data-priority="3">Date</th>
                <th data-priority="4">Amount</th>
                <th data-priority="5">Balance</th>
                <th></th>
              </tr>
              </thead>
              <tbody>
              <% @transactions.each do |transaction| %>
                  <tr>
                    <td><%= transaction.fromAccount %></td>
                    <td><%= transaction.created_at.to_formatted_s(:long_ordinal) %></td>
                    <td><%= transaction.amount %></td>
                    <td><%= transaction.balance %></td>
                    <td></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </li>
  </ul>

</div>

<%= link_to 'Back', balance_path, 'data-role' => "button", 'data-icon' => "back", 'data-iconpos' => "left" %>

app/views/transaction/new.html.erb
<% provide(:title, 'Transfer') %>

<div class="unshuttered">
  <%= form_for(@transaction, :url => transfer_path(@transaction), :as => :transfer) do |f| %>
      <% if @transaction.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction:</h2>

            <ul>
              <% @transaction.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
        <div class="form-element qp-name-row">
          <div class="ui-grid-a">
            <div class="ui-block-a"></div>
            <div class="ui-block-b">
              <%= link_to 'New Friend', transfer_new_path, 'data-role' => "button", :class => 'secondary-button',
                          'data-theme' => 'dva', 'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
            </div>
          </div>
          <%= f.label :toAccount, 'Transfer to' %>
          <%= f.select :toAccount, [['Account No.   /   Email', nil]], {}, {:class => 'friends-list'} %>
        </div>
        <div class="form-element qp-name-row">
          <%= f.label :fromAccount, 'Pay from' %>
          <%= f.select :fromAccount, @accounts -%>
        </div>
        <div class="form-element qp-name-row">
          <%= f.label :amount, 'Amount $' %>
          <%= f.text_field :amount, :step => 0.01, :type => 'number' %>
        </div>
        <div class="form-element qp-name-row">
          <%= f.label :memo %>
          <%= f.text_field :memo, :maxlength => 200 %>
        </div>
      </div>
      <div class="ui-grid-a">
        <div class="ui-block-a">
          <%= link_to 'Cancel', root_path, :class => 'cancel secondary-button', 'data-role' => "button",
                      'data-theme' => 'dva', 'data-icon' => "back" %>
        </div>
        <div class="ui-block-b">
          <%= f.submit 'Transfer', 'data-role' => "button", 'data-theme' => 'dva',
                       'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
        </div>
      </div>

  <% end %>

  <%= link_to 'QR Transfer', token_path, 'data-role' => "button", 'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
</div>

app/views/transaction/qrcode.html.erb
<% provide(:title, 'Transfer') %>

<table class="qr">
  <% @qr.modules.each_index do |x| -%>
      <tr>
        <% @qr.modules.each_index do |y| -%>
            <% if @qr.dark?(x, y) -%>
                <td class="black"/>
            <% else -%>
                <td class="white"/>
            <% end -%>
        <% end -%>
      </tr>
  <% end -%>
</table>

app/views/transaction/token.html.erb
<% provide(:title, 'Transfer') %>
<%= form_for(@token, :url => token_path(@token), :as => :token) do |f| %>
    <% if @token.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@token.errors.count, "error") %> prohibited this transaction:</h2>
          <ul>
            <% @token.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-wrapper ui-corner-all ui-listview ui-listview-inset ui-shadow">
      <div class="form-element qp-name-row">
        <%= f.label :account_number, 'Pay from' %>
        <br/>
        <%= f.select :account_number, @accounts %>
      </div>
      <div class="form-element qp-name-row">
        <%= f.label :amount, 'Amount $' %>
        <br/>
        <%= f.text_field :amount, :step => 0.01, :type => 'number' %>
      </div>
    </div>
    <div class="ui-grid-a">
      <div class="ui-block-a">
        <%= link_to 'Cancel', root_path, :class => 'cancel secondary-button', 'data-role' => "button",
                    'data-theme' => 'dva', 'data-icon' => "back" %>
      </div>
      <div class="ui-block-b">
        <%= f.submit 'Create QR-token', 'data-role' => "button", 'data-theme' => 'dva',
                     'data-icon' => "arrow-r", 'data-iconpos' => "right" %>
      </div>
    </div>

<% end %>